# ####SEQUENTIAL CODE
# import numpy as np


# def calculate_fitness(route,
#                       distance_matrix):
#     """
#     calculate_fitness function: total distance traveled by the car.

#     Parameters:
#         - route (list): A list representing the order of nodes visited in the route.
#         - distance_matrix (numpy.ndarray): A matrix of the distances between nodes.
#             A 2D numpy array where the element at position [i, j] represents the distance between node i and node j.
#     Returns:
#         - float: The negative total distance traveled (negative because we want to minimize distance).
#            Returns a large negative penalty if the route is infeasible.
#     """
#     total_distance = 0
    
#     # add your code here.
#     for i in range(len(route) - 1):
#         node1, node2 = route[i], route[i + 1]
#         distance = distance_matrix[node1, node2]
        
#         if distance == 10000: 
#             return -1e6

#         total_distance += distance
        
#     return -total_distance


# def select_in_tournament(population,
#                          scores,
#                          number_tournaments=4,
#                          tournament_size=3):
#     """
#     Tournament selection for genetic algorithm.

#     Parameters:
#         - population (list): The current population of routes.
#         - scores (np.array): The calculate_fitness scores corresponding to each individual in the population.
#         - number_tournaments (int): The number of the tournamnents to run in the population.
#         - tournament_size (int): The number of individual to compete in the tournaments.

#     Returns:
#         - list: A list of selected individuals for crossover.
#     """
#     selected = []
    
#     # add your code here.
#     for _ in range(number_tournaments):
#         idx=np.random.choice(len(population),tournament_size,replace=False)
#         best_idx = idx[np.argmax(scores[idx])]
#         selected.append(population[best_idx])
    
#     return selected


# def order_crossover(parent1, parent2):
#     """
#     Order crossover (OX) for permutations.

#     Parameters:
#         - parent1 (list): The first parent route.
#         - parent2 (list): The second parent route.

#     Returns:
#         - list: The offspring route generated by the crossover.
#     """
#     size = len(parent1)
#     start, end = sorted(np.random.choice(range(size), 2, replace=False))
#     offspring = [None] * size
#     offspring[start:end + 1] = parent1[start:end + 1]
#     fill_values = [x for x in parent2 if x not in offspring[start:end + 1]]
#     idx = 0
#     for i in range(size):
#         if offspring[i] is None:
#             offspring[i] = fill_values[idx]
#             idx += 1
#     return offspring


# def mutate(route,
#            mutation_rate = 0.1):
#     """
#     Mutation operator: swap two nodes in the route.

#     Parameters:
#         - route (list): The route to mutate.
#         - mutation_rate (float): The chance to mutate an individual.
#     Returns:
#         - list: The mutated route.
#     """
#     if np.random.rand() < mutation_rate:
#         i, j = np.random.choice(len(route), 2, replace=False)
#         route[i], route[j] = route[j], route[i]
#     return route

# def generate_unique_population(population_size, num_nodes):
#     """
#     Generate a unique population of individuals for a genetic algorithm.

#     Each individual in the population represents a route in a graph, where the first node is fixed (0) and the 
#     remaining nodes are a permutation of the other nodes in the graph. This function ensures that all individuals
#     in the population are unique.

#     Parameters:
#         - population_size (int): The desired size of the population.
#         - num_nodes (int): The number of nodes in the graph, including the starting node.

#     Returns:
#         - list of lists: A list of unique individuals, where each individual is represented as a list of node indices.
#     """
#     population = set()
#     while len(population) < population_size:
#         individual = [0] + list(np.random.permutation(np.arange(1, num_nodes)))
#         population.add(tuple(individual))
#     return [list(ind) for ind in population]


"""
Genetic Algorithm Helper Functions
-----------------------------------
"""

import numpy as np

def calculate_fitness(route, distance_matrix):
    """
    Calculate the total distance of a given route using the provided distance matrix.

    Args:
        route (list): A list of city indices representing the travel route.
        distance_matrix (numpy array): A 2D array where [i, j] represents the distance from city i to city j.

    Returns:
        float: The negative total distance (to enable minimization). If the route is infeasible, a large penalty is applied.
    """
    total_distance = 0
    for i in range(len(route) - 1):
        node1, node2 = route[i], route[i + 1]
        distance = distance_matrix[node1, node2]

        if distance == 10000:  # Infeasible route check
            return -1e6  # Large negative penalty

        total_distance += distance
    return -total_distance  # Return negative for minimization


def adaptive_mutation_rate(generation, max_generations, initial_rate=0.1, final_rate=0.01):
    """
    Adjust the mutation rate dynamically as the generations progress. The rate decreases over time.

    Args:
        generation (int): The current generation number.
        max_generations (int): The total number of generations.
        initial_rate (float, optional): The initial mutation rate at generation 0. Default is 0.1.
        final_rate (float, optional): The final mutation rate at the last generation. Default is 0.01.

    Returns:
        float: The adjusted mutation rate for the current generation.
    """
    return initial_rate - (initial_rate - final_rate) * (generation / max_generations)


def local_search(route, distance_matrix):
    """
    Perform a local search on the given route to try and improve it by reversing segments.

    Args:
        route (list): A list representing the order of nodes in the route.
        distance_matrix (numpy array): A 2D matrix representing the distances between nodes.

    Returns:
        list: The improved route after performing the local search.
    """
    improved = True
    while improved:
        improved = False
        for i in range(1, len(route) - 1):
            for j in range(i + 1, len(route)):
                # Reverse part of the route and check if it's better
                new_route = route[:i] + route[i:j][::-1] + route[j:]
                if calculate_fitness(new_route, distance_matrix) < calculate_fitness(route, distance_matrix):
                    route = new_route
                    improved = True
    return route


def select_in_tournament(population, scores, number_tournaments=4, tournament_size=3):
    """
    Perform tournament selection on the population.

    Args:
        population (list): The list of individuals in the population.
        scores (list): The fitness scores corresponding to each individual.
        number_tournaments (int, optional): The number of tournaments to run. Default is 4.
        tournament_size (int, optional): The number of individuals in each tournament. Default is 3.

    Returns:
        list: A list of selected individuals based on tournament selection.
    """
    selected = []
    for _ in range(number_tournaments):
        # Randomly select individuals for the tournament
        idx = np.random.choice(len(population), tournament_size, replace=False)
        # Select the best individual (lowest fitness score)
        best_idx = idx[np.argmin(scores[idx])]
        selected.append(population[best_idx])
    return selected


def order_crossover(parent1, parent2):
    """
    Perform Order Crossover (OX) to create an offspring route.

    Args:
        parent1 (list): A list representing the first parent route.
        parent2 (list): A list representing the second parent route.

    Returns:
        list: A list representing the offspring route after crossover.
    """
    size = len(parent1)
    start, end = sorted(np.random.choice(range(size), 2, replace=False))

    # Initialize offspring with None values
    offspring = [None] * size
    offspring[start:end + 1] = parent1[start:end + 1]

    # Fill remaining positions with genes from parent2
    fill_values = [x for x in parent2 if x not in offspring[start:end + 1]]
    idx = 0
    for i in range(size):
        if offspring[i] is None:
            offspring[i] = fill_values[idx]
            idx += 1

    return offspring


def mutate(route, mutation_rate=0.1):
    """
    Perform mutation on the given route by swapping two random cities.

    Args:
        route (list): A list representing the order of nodes in the route.
        mutation_rate (float, optional): The probability of performing a mutation. Default is 0.1.

    Returns:
        list: The mutated route.
    """
    if np.random.rand() < mutation_rate:
        i, j = np.random.choice(len(route), 2, replace=False)
        route[i], route[j] = route[j], route[i]
    return route


def generate_unique_population(population_size, num_nodes):
    """
    Generate a unique population of individuals, where each individual represents a possible route.

    Args:
        population_size (int): The number of individuals to generate.
        num_nodes (int): The total number of nodes (cities) in the problem.

    Returns:
        list: A list of unique individuals (routes).
    """
    population = set()
    while len(population) < population_size:
        # Generate random routes, ensuring that node 0 is the starting point
        individual = [0] + list(np.random.permutation(np.arange(1, num_nodes)))
        population.add(tuple(individual))  # Use tuple to ensure uniqueness
    return [list(ind) for ind in population]

